LightLib.Web/Models/Branch/BranchDetailModel.cs
using System.Collections.Generic;

namespace LightLib.Web.Models.Branch {
    public class BranchDetailModel {
        public int Id { get; set; }
        public string Address { get; set; }
        public string BranchName { get; set; }
        public string BranchOpenedDate { get; set; }
        public string Telephone { get; set; }
        public bool IsOpen { get; set; }
        public string Description { get; set; }
        public int NumberOfPatrons { get; set; }
        public int NumberOfAssets { get; set; }
        public decimal TotalAssetValue { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<string> HoursOpen { get; set; }
    }
}

LightLib.Web/Models/Branch/BranchIndexModel.cs
using LightLib.Models;
using LightLib.Models.DTOs;

namespace LightLib.Web.Models.Branch {
    public class BranchIndexModel {
        public PaginationResult<LibraryBranchDto> PageOfBranches { get; set; }
    }
}

LightLib.Web/Controllers/BranchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LightLib.Models;
using LightLib.Models.DTOs;
using LightLib.Service.Interfaces;
using LightLib.Web.Models.Branch;
using Microsoft.AspNetCore.Mvc;

namespace LightLib.Web.Controllers {
    public class BranchController : LibraryController {
        private readonly ILibraryBranchService _branchService;

        public BranchController(ILibraryBranchService branchService) {
            _branchService = branchService;
        }

        public async Task<IActionResult> Index([FromQuery] int page = 1, [FromQuery] int perPage = 10) {
            var paginatedBranches = await _branchService.GetPaginated(page, perPage);

            if (paginatedBranches.Results.Any()) {
                foreach (var branch in paginatedBranches.Results) {
                    var branchId = branch.Id;
                    branch.IsOpen = await _branchService.IsBranchOpen(branchId);
                    branch.NumberOfAssets = await _branchService.GetAssetCount(branchId);
                    branch.NumberOfPatrons = await _branchService.GetPatronCount(branchId);
                }

                var model = new BranchIndexModel {
                    PageOfBranches = paginatedBranches 
                };

                return View(model);
            }
            
            var emptyModel = new BranchIndexModel {
                PageOfBranches = new PaginationResult<LibraryBranchDto> {
                    Results = new List<LibraryBranchDto>(),
                    PageNumber = page,
                    PerPage = perPage
                }
            };

            return View(emptyModel);
        }
        
        public async Task<IActionResult> Detail(int id) {

            var serviceResult = await _branchService.Get(id);

            var patronCount = await _branchService.GetPatronCount(id);
            var assetsCount = await _branchService.GetAssetCount(id);
            var assetsValue = await _branchService.GetAssetsValue(id);
            var branchHoursResult = await _branchService.GetBranchHours(id);
            var branchHours = branchHoursResult ?? new List<string>();

            var model = new BranchDetailModel {
                BranchName = serviceResult.Name,
                Description = serviceResult.Description,
                Address = serviceResult.Address,
                Telephone = serviceResult.Telephone,
                BranchOpenedDate = serviceResult.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfPatrons = patronCount,
                NumberOfAssets = assetsCount,
                TotalAssetValue = assetsValue,
                ImageUrl = serviceResult.ImageUrl,
                HoursOpen = branchHours
            };

            return View(model);
        }
    }
}

LightLib.Web/Views/Branch/Detail.cshtml
@model LightLib.Web.Models.Branch.BranchDetailModel
@{
    ViewBag.Title = $"{@Model.BranchName} Branch";
}

<section>
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark" 
       style="background-image: 
                linear-gradient(to bottom, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.95)), 
                url(@Url.Content($"~/images/libraries/{Model.ImageUrl}"));
                background-position: center;
                background-repeat: repeat;
                background-size: auto;">
    <div class="row">
    <div class="col-md-8 px-0">
      <h1 class="display-1 fw-bold">@Model.BranchName</h1>
      <p class="lead my-3">@Model.Description</p>
    </div>
    <div class="col-md-4 px-0">
      <figure class="figure">
        <img
          src="@Url.Content($"~/images/libraries/{Model.ImageUrl}")"
          class="figure-img rounded img-thumbnail img-fluid"
          alt="Image of @Model.BranchName">
        <figcaption class="figure-caption text-light">
          Photo of @Model.BranchName
        </figcaption>
      </figure>
    </div>
    </div>
  </div>
</section>

<hr />

<section>
  <div class="container">
    <div class="row">
      <h3>Branch Data</h3>
      <div class="col-6">
        <h4>Branch Info</h4>
        <table class="table table-sm">
          <tr>
            <td>Address</td>
            <td>@Model.Address</td>
          </tr>
          <tr>
            <td>Telephone</td>
            <td>@Model.Telephone</td>
          </tr>
          <tr>
            <td>Date Established</td>
            <td>@Model.BranchOpenedDate</td>
          </tr>
        </table>
      </div>
      <div class="col-6">
        <h4>Branch Asset Summary</h4>
        <table class="table table-sm">
          <tr>
            <td>Registered Patrons</td>
            <td>@Model.NumberOfPatrons</td>
          </tr>
          <tr>
            <td>Total Asset Count</td>
            <td>@Model.NumberOfAssets</td>
          </tr>
          <tr>
            <td>Total Asset Value</td>
            <td>@Model.TotalAssetValue</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</section>

<hr />

<section>
  <div class="container">
  <div class="row">
    <h3>Schedule</h3>
    <div class="col-lg-12">
      <div id="branchHours">
      <table class="table table-sm">
          @foreach (var day in @Model.HoursOpen) {
            <tr>
                <td>@day</td>
            </tr>
          }
      </table>
      </div>
    </div>
  </div>
  </div>
</section>

LightLib.Web/Views/Branch/Index.cshtml
@using LightLib.Web.Controllers
@model LightLib.Web.Models.Branch.BranchIndexModel
@{
    ViewBag.Title = "Branches";
}

<h2 class="lms-section-heading">
    Library Branches 
</h2>

<div class="row">
    <section>
        <p>
            <strong>Branches</strong> consist of individual library locations.
        </p> 
        <p>
            Use this page view details about each Branch in the system.
        </p>
    </section>
</div>

<div class="row">
    <div class="col-12">
        <button class="btn btn-primary btn-sm">
            Register New Library Branch 
        </button>
    </div>
</div>

<hr />

<div class="row">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var branch in Model.PageOfBranches.Results) {
            <div class="col">
                <div class="card h-100">
                    <a asp-controller="Branch" asp-action="Detail" asp-route-id="@branch.Id">
                        <img src="@Url.Content($"~/images/libraries/{branch.ImageUrl}")" class="card-img-top" alt="Image of @branch.Name">
                    </a>
                    <div class="card-body">
                        <a asp-controller="Branch" asp-action="Detail" asp-route-id="@branch.Id">
                            <h5 class="card-title">@branch.Name</h5>
                        </a>
                        <p class="card-text">@branch.Description</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Number of Patrons: @branch.NumberOfPatrons</small>
                    </div>
                </div>
            </div>
        }
    </div>
</div>