LightLib.Web/Models/Patron/PatronDetailModel.cs
using System;
using LightLib.Models;
using LightLib.Models.DTOs;

namespace LightLib.Web.Models.Patron {
    public class PatronDetailModel {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? LibraryCardId { get; set; }
        public string Address { get; set; }

        public DateTime DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string HomeLibrary { get; set; }
        public decimal? OverdueFees { get; set; }
        public string HasBeenMemberFor { get; set; }
        public PaginationResult<CheckoutDto> AssetsCheckedOut { get; set; }
        public PaginationResult<CheckoutHistoryDto> CheckoutHistory { get; set; }
        public PaginationResult<HoldDto> Holds { get; set; }
    }
}

LightLib.Web/Models/Patron/PatronIndexModel.cs
using LightLib.Models;
using LightLib.Models.DTOs;

namespace LightLib.Web.Models.Patron {
    public class PatronIndexModel {
        public PaginationResult<PatronDto> PageOfPatrons { get; set; }
    }
}

LightLib.Web/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LightLib.Models;
using LightLib.Models.DTOs;
using LightLib.Service.Helpers;
using LightLib.Service.Interfaces;
using LightLib.Web.Models.Patron;
using Microsoft.AspNetCore.Mvc;

namespace LightLib.Web.Controllers
{

    public class PatronController : LibraryController
    {
        private readonly IPatronService _patronService;

        public PatronController(IPatronService patronService)
        {
            _patronService = patronService;
        }

        public async Task<IActionResult> Index([FromQuery] int page = 1, [FromQuery] int perPage = 10)
        {

            var patrons = await _patronService.GetPaginated(page, perPage);

            if (patrons != null && patrons.Results.Any())
            {
                var viewModel = new PatronIndexModel
                {
                    PageOfPatrons = patrons
                };

                return View(viewModel);
            }

            var emptyModel = new PatronIndexModel
            {
                PageOfPatrons = new PaginationResult<PatronDto>
                {
                    Results = new List<PatronDto>(),
                    PerPage = perPage,
                    PageNumber = page
                }
            };

            return View(emptyModel);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var patron = await _patronService.Get(id);
            var assetsCheckedOut = await _patronService.GetPaginatedCheckouts(patron.Id, 1, 10);
            var checkoutHistory = await _patronService.GetPaginatedCheckoutHistory(patron.Id, 1, 10);
            var holds = await _patronService.GetPaginatedHolds(patron.Id, 1, 10);
            var memberLengthOfTime = TimeSpanHumanizer.GetReadableTimespan(DateTime.UtcNow - patron.CreatedOn);

            var model = new PatronDetailModel()
            {
                Id = patron.Id,
                FirstName = patron.FirstName,
                LastName = patron.LastName,
                Email = patron.Email,
                LibraryCardId = patron.LibraryCardId,
                Address = patron.Address,
                Telephone = patron.Telephone,
                HomeLibrary = patron.HomeLibrary,
                OverdueFees = patron.OverdueFees,
                AssetsCheckedOut = assetsCheckedOut,
                CheckoutHistory = checkoutHistory,
                Holds = holds,
                HasBeenMemberFor = memberLengthOfTime
            };

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> AddOrEdit(PatronDto patron)
        {
            return await _patronService.Add(patron);

        }

        public async Task<bool> DeletePatron(int? id)
        {
            return await _patronService.Delete(id);


        }

        [HttpPost]
        public async Task<bool> EditPatron(PatronDto patron)
        {
            return await _patronService.UpdatePatron(patron);
        }
    }
}

LightLib.Web/Views/Patron/Create.cshtml
@model LightLib.Web.Models.Patron.PatronDetailModel
@{
    ViewData["Title"] = "Create Patron";
}
<section>
    <div class="row">
    <div class="col-md-6">
        <form asp-action="AddorEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h3>Welcome to LMS! Let's Add New Patron</h3> 
            <input type="hidden" asp-for="Id" />
            <div class="form-group">

                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" required minlength="5" maxlength="15" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" required maxlength="15"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Address"></label>
 
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="DateOfBirth"></label>
                <input asp-for="DateOfBirth" class="form-control" required />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" type="email" required/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone"></label>
                <input asp-for="Telephone" class="form-control" maxlength="10" required/>
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LibraryCardId"></label>
                <input asp-for="LibraryCardId" class="form-control" required />
                <span asp-validation-for="LibraryCardId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeLibrary"></label>
                <input asp-for="HomeLibrary" class="form-control" required/>
                <span asp-validation-for="HomeLibrary" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                </div>
                <div  class="form-group col-md-6">
                    <a asp-action="Index"  class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>
</section>

LightLib.Web/Views/Patron/Detail.cshtml
@model LightLib.Web.Models.Patron.PatronDetailModel
@{
    ViewBag.Title = $"Patron: {@Model.LastName}, {@Model.FirstName}";
}

<section>
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="row">
      <div class="col-md-8 px-0">
        <h1 class="display-1 fw-bold">@Model.FirstName @Model.LastName</h1>
        <p class="lead my-3">Member for @Model.HasBeenMemberFor</p>
      </div>
      <div class="col-4">
        <h4>Patron Info</h4>
        <table class="table table-sm table-dark text-white">
          <tr>
            <td>Address</td>
            <td>@Model.Address</td>
          </tr>
          <tr>
            <td>Telephone</td>
            <td>@Model.Telephone</td>
          </tr>
          <tr>
            <td>Email</td>
            <td>@Model.Email</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</section>

<hr />

<section>
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h4>Current Checked Out Assets</h4>
        @if (!Model.AssetsCheckedOut.Results.Any()) {
          <p>
            No items checked out.
          </p>
        } else {
          <table class="table table-sm">
          </table>
        }
      </div>
      <div class="col-6">
        <h4>Current Holds</h4>
        @if (!Model.Holds.Results.Any()) {
          <p>
            No items currently on hold.
          </p>
        } else {
          <table class="table table-sm">
          </table>
        }
      </div>
    </div>
  </div>
</section>

<hr />

LightLib.Web/Views/Patron/Edit.cshtml
@model LightLib.Web.Models.Patron.PatronDetailModel
@{
    ViewData["Title"] = "Edit Patron";
}
<section>
    <div class="row">
    <div class="col-md-6">
        <form asp-action="EditPatron">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control"/>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control"/>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="DateOfBirth"></label>
                <input asp-for="DateOfBirth" class="form-control"/>
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone"></label>
                <input asp-for="Telephone" class="form-control"/>
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LibraryCardId"></label>
                <input asp-for="LibraryCardId" class="form-control"/>
                <span asp-validation-for="LibraryCardId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeLibrary"></label>
                <input asp-for="HomeLibrary" class="form-control"/>
                <span asp-validation-for="HomeLibrary" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                </div>
                <div  class="form-group col-md-6">
                    <a asp-action="Index"  class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>
</section>

LightLib.Web/Views/Patron/Index.cshtml
@model LightLib.Web.Models.Patron.PatronIndexModel
@{
    ViewBag.Title = "Patrons";
}

<h2 class="lms-section-heading">
    Library Patrons
</h2>

<div class="row">
    <section>
        <p>
            <strong>Patrons</strong> make up the body of library users across all branches.
        </p> 
        <p>
            Use this page to add or remove Patrons from the system, replace lost library cards, view or manage fees.
        </p>
    </section>
</div>

<div class="row">
    <div class="col-12">
        <form  class="card p-3" asp-action="Create">      
            <input type="submit"  class="btn btn-primary btn-sm" value="Add New Patron"/> 
        </form>
    </div>
</div>

<hr />

<div class="row">
    <div class="container container-fluid">
        <table class="table table-responsive-sm table-hover">
            <thead class="thead-dark">
            <tr>
                <th scope="col" style="width: 30%">Details</th>
                <th scope="col" style="width: 10%">Patron Id</th>
                <th scope="col" style="width: 20%">Last</th>
                <th scope="col" style="width: 20%">First</th>
                <th scope="col" style="width: 25%">Email</th>
                <th scope="col" style="width: 5%">Fees</th>
                <th scope="col" style="width: 5%">Action</th>


            </tr>
            </thead>
            <tbody>
            @foreach (var patron in Model.PageOfPatrons.Results) {
                <a asp-controller="Patron" asp-action="Detail" asp-route-id="@patron.Id">
                    <tr>
                        <th scope="row">
                            <a asp-controller="Patron" asp-action="Detail" asp-route-id="@patron.Id">
                                View Details
                            </a>
                        </th>
                        <td>@patron.Id</td>
                        <td>@patron.LastName</td>
                        <td>@patron.FirstName</td>
                        <td>@patron.Email</td>
                        <td>$@Math.Round(patron.OverdueFees, 2)</td>
                        <td class="row">
                            <a asp-controller="Patron" asp-action="DeletePatron" asp-route-id="@patron.Id">Delete</a>
                            <a asp-controller="Patron" asp-action="Edit" asp-route-id="@patron.Id">Update</a>

                         </td>
                    </tr>
                </a>
            }
            </tbody>
        </table>
        
        <nav aria-label="Patron Table Navigation Bottom">
          @{
              var previousPage = (Model.PageOfPatrons.PageNumber - 1);
              var nextPage = (Model.PageOfPatrons.PageNumber + 1);
              var prevDisabled = !Model.PageOfPatrons.HasPreviousPage ? "disabled" : "";
              var nextDisabled = !Model.PageOfPatrons.HasNextPage ? "disabled" : "";
          }
          <ul class="pagination justify-content-end">
              <li class="page-item small">
                  @Html.ActionLink("Previous", "Index", "Patron", new { page = previousPage }, new { @class="page-link" })
              </li>
              <li class="page-item small">
                  @Html.ActionLink("Next", "Index", "Patron", new { page = nextPage }, new { @class="page-link" })
              </li>
          </ul>
        </nav>
    </div>
</div>



   

                

LightLib.Web/Views/Patron/PayFees.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}